swim/record/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView

from . import views


# app_name = 'record'

urlpatterns = [
    url(r'^login', LoginView.as_view(template_name='record/login.html'), name='login'),
    url(r'^logout', LogoutView.as_view(template_name='record/logout.html'), name='logout'),

    url(r'^new', views.new, name='new'),
    url(r'^create', views.create, name='create'),

    url(r'^$', views.Index, name='index'),

    url(r'^input_data/$', views.Input_Data, name='input_data'),

    url(r'^ajax_chart/', views.ajax_chart, name='ajax_chart'),
    url(r'^chart/$', views.ChartView, name='chart_view'),

    url(r'^player_list/$', views.Player_List, name='player_list'),
    url(r'^player/(?P<pk>[0-9]+)/$', views.Player_Info.as_view(), name='player_info'),
    url(r'^player_update/(?P<pk>[0-9]+)/$', views.Player_Update.as_view(), name='player_update'),


    url(r'^top/$', views.TopPage.as_view(), name='top'),
    url(r'^top/(?P<pk>[0-9]+)/$', views.Training_Detail.as_view(), name='detail'),
]

swim/swim/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^record/', include('record.urls')),
]

swim/record/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

SEX_CHOICES = (
    ('M', 'Man'),
    ('W', 'Woman'),
    ('O', 'Other')
)

STYLE_CHOICES = (
    ('Fr', 'Fr'),
    ('Ba', 'Ba'),
    ('Br', 'Br'),
    ('Fly', 'Fly'),
    ('IM', 'IM'),

)

DISTANCE_CHOICES = (
    (25, 25),
    (50, 50),
    (100, 100),
    (200, 200),
    (400, 400),
    (800, 800),
)

ONE_TO_TEN_CHOICES = [
    (num, num) for num in range(0, 11)
]

ONE_TO_SIXTY_CHOICE = [
    (num, num) for num in range(0, 60)
]


class Menue(models.Model):
    menue_name = models.CharField(max_length=15, verbose_name='メニュー')

    def __str__(self):
        return self.menue_name


class DayMenu(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(default=timezone.now, null=True, blank=False)
    score = models.PositiveIntegerField('点数', null=True, blank=True)
    reflection = models.TextField('感想', max_length=1000, null=True, blank=True)

    def get_trainings(self):
        t = TrainingMenu.objects.filter(daymenu=self)
        return [i for i in t]

    def __str__(self):
        return '{}, {}, {}'.format(self.pk, self.user, self.date)


class TrainingMenu(models.Model):
    daymenu = models.ForeignKey(DayMenu, on_delete=models.CASCADE, null=True, blank=True, related_name='trainingmenus')
    order = models.PositiveIntegerField('メニューNo.', null=True, blank=True)
    menu_name = models.ForeignKey(Menue, on_delete=models.CASCADE, null=True, blank=True)
    style = models.CharField(choices=STYLE_CHOICES, max_length=10, null=True, blank=False)
    distance = models.IntegerField(choices=DISTANCE_CHOICES, null=False)
    # graph = views.make_img()

    def get_times(self):
        t = Result_Time.objects.filter(trainingmenu=self)
        return [i.time for i in t]

    def __str__(self):
        return '{}, {}'.format(self.daymenu.pk, self.menu_name)


class Result_Time(models.Model):
    trainingmenu = models.ForeignKey(TrainingMenu, on_delete=models.CASCADE, null=True, blank=True, related_name='times')
    order = models.IntegerField('本数', null=True)
    time = models.FloatField('タイム[s]', null=True, blank=True)
    rest = models.NullBooleanField('レスト', blank=True, default=False)

    def __str__(self):
        return '{}'.format(self.order)


class Rap_Time(models.Model):
    result_time = models.ForeignKey(Result_Time, on_delete=models.CASCADE, null=True, blank=True, related_name='raps')
    time = models.FloatField('タイム[s]', null=True, blank=True)

    def __str__(self):
        return '{}, {}'.format(int(self.pk)*50, self.time)


class User_Info(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    familyname = models.CharField('姓', max_length=15, null=True, blank=True)
    firstname = models.CharField('名', max_length=15, null=True, blank=True)
    sex = models.CharField('性別', max_length=5, choices=SEX_CHOICES, null=True, blank=True)
    generation = models.PositiveIntegerField('期', null=True, blank=True)
    style = models.CharField(choices=STYLE_CHOICES, max_length=10, null=True, blank=True)
    cource = models.PositiveIntegerField('コース', null=True, blank=True)
    is_manager = models.BooleanField('マネジャー', default=False)
    is_courch = models.BooleanField('コーチ', default=False)

    def __str__(self):
        return self.user.username

swim/record/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from .models import Menue, DayMenu, TrainingMenu, Result_Time, User_Info
import os
import pandas as pd


path = os.path.join(os.path.join(os.path.dirname(__file__), 'Result_all.csv'))
df = pd.read_csv(path)


class User_Info_Form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(User_Info_Form, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = User_Info
        # fields = '__all__'
        exclude = ['user', 'is_manager', 'is_courch', ]


class User_Update_Form(User_Info_Form, UserChangeForm):

    class Meta:
        model = User
        # model = User_Info
        fields = '__all__'
        # exclude = ['user', 'is_manager', 'is_courch', ]


class Menue_Form(forms.ModelForm):
    class Meta:
        model = Menue
        fields = '__all__'


class DayMenu_Form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DayMenu_Form, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = DayMenu
        fields = '__all__'


class TrainingMenu_Form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TrainingMenu_Form, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = TrainingMenu
        fields = '__all__'
        # menue_name = forms.ModelChoiceField(Menue.objects)


class Result_Time_Form(forms.ModelForm):
    NUMBER = [
        (num, num) for num in range(0, 10)
    ]
    m_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_10 custom-select'}))
    m_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_1 custom-select'}))
    s_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_10 custom-select'}))
    s_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_1 custom-select'}))
    ms_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_10 custom-select'}))
    ms_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_1 custom-select'}))

    rest = forms.BooleanField(required=False)

    class Meta:
        model = Result_Time
        fields = '__all__'
        widgets = {
            'time_minutes': forms.NumberInput(attrs={
                'name': 'time_minutes[]',
            }),
            'time_seconds': forms.NumberInput(attrs={
                'name': 'time_seconds[]',
            }),
            'time_seconds_micro': forms.NumberInput(attrs={
                'name': 'time_seconds_micro[]',
            }),
        }


class Rap_Time_Form(forms.Form):

    NUMBER = [
        (num, num) for num in range(0, 10)
    ]

    m_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_1_r custom-select'}))
    s_10_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_10_r custom-select'}))
    s_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_1_r custom-select'}))
    ms_10_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_10_r custom-select'}))
    ms_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_1 custom-select'}))


class Select_Form(forms.Form):
    year_list = sorted(list(set(df.Year.values)))
    style_list = sorted(list(set(df.Style.values)))
    distance_list = sorted(list(set(df.Distance.values)))
    sex_list = sorted(list(set(df.Sex.values)))

    YEAR_CHOICES = [(year, year) for year in year_list]
    STYLE_CHOICES = [(style, style) for style in style_list]
    DISTANCE_CHOICES = [(distance, distance) for distance in distance_list]
    SEX_CHOICES = [(sex, sex) for sex in sex_list]

    YEAR_CHOICES.append((year_list, 'all'))
    STYLE_CHOICES.append((style_list, 'all'))
    DISTANCE_CHOICES.append((distance_list, 'all'))
    SEX_CHOICES.append((sex_list, 'all'))


    year = forms.ChoiceField(choices=YEAR_CHOICES, label='年度', widget=forms.Select(attrs={'class': 'year custom-select'}))
    sex = forms.ChoiceField(choices=SEX_CHOICES, label='性別', widget=forms.Select(attrs={'class': 'sex custom-select'}))
    style = forms.ChoiceField(choices=STYLE_CHOICES, label='スタイル', widget=forms.Select(attrs={'class': 'style custom-select'}))
    # sex = forms.MultipleChoiceField(choices=SEX_CHOICES, label='性別', widget=forms.CheckboxSelectMultiple())
    # style = forms.ChoiceField(choices=STYLE_CHOICES, label='スタイル')
    distance = forms.ChoiceField(choices=DISTANCE_CHOICES, label='距離', widget=forms.Select(attrs={'class': 'distance custom-select'}))






# class Menu_Test_Form(forms.Form):
#     from record.models import STYLE_CHOICES, DISTANCE_CHOICES
#
#     date = forms.DateField(initial=timezone.now, widget=forms.SelectDateWidget(attrs={'class': 'form-control'}))
#
#     menu = forms.ChoiceField(choices=[(i.menue_name, i.menue_name) for i in Menue.objects.all()], widget=forms.Select(attrs={'class': 'custom-select'}))
#
#     style = forms.ChoiceField(choices=STYLE_CHOICES, widget=forms.Select(attrs={'class': 'custom-select'}))
#     distance = forms.ChoiceField(choices=DISTANCE_CHOICES, widget=forms.Select(attrs={'class': 'custom-select'}))
#     number = forms.ChoiceField(choices=[(num, num) for num in range(1, 31)], widget=forms.Select(attrs={'class': 'custom-select'}))
#     score = forms.ChoiceField(choices=[(num, num) for num in range(1, 6)], widget=forms.Select(attrs={'class': 'custom-select'}))
#     reflection = forms.CharField(max_length=1000, widget=forms.Textarea(attrs={'class': 'form-control'}))




# class Time_Form(forms.Form):
#     NUMBER = [
#         (num, num) for num in range(0, 10)
#     ]
#
#     m_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_10 custom-select'}))
#     m_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_1 custom-select'}))
#     s_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_10 custom-select'}))
#     s_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_1 custom-select'}))
#     ms_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_10 custom-select'}))
#     ms_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_1 custom-select'}))
#
#     rest = forms.BooleanField(required=False)


# class Rap_Form(forms.Form):
#     NUMBER = [
#         (num, num) for num in range(0, 10)
#     ]
#
#     m_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_1_r custom-select'}))
#     s_10_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_10_r custom-select'}))
#     s_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_1_r custom-select'}))
#     ms_10_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_10_r custom-select'}))
#     ms_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_1 custom-select'}))

# class Sample_Form(forms.Form):
#     def __init__(self, num=3, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for i in range(self.num):
#             self['value_{}'.format(i)] = forms.CharField(max_length=10)

    # NUMBER = [
    #     (num, num) for num in range(0, 10)
    # ]
    #
    # m_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_10 custom-select'}))
    # m_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_1 custom-select'}))
    # s_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_10 custom-select'}))
    # s_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_1 custom-select'}))
    # ms_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_10 custom-select'}))
    # ms_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_1 custom-select'}))
    #
    # rest = forms.BooleanField(required=False)

swim/record/templates/record/chart_view.html
{% extends "base.html" %} {% block body %}

<div class="row">
  <div class="jumbotron bg-light">
    <div class="col-sm">
      <form id='school_name' action="{% url 'ajax_chart' %}" method="get">
        <label for="school_name_selector">学校名:</label>
        <select id="school_name_selector" name="school_name" class="custom-select">
            {% for school_name in school_names %}
            <option>
            {{ school_name }}
            </option>
            {% endfor %}
        </select>
      </form>
      <table class="table table-striped">{{select_form.as_table}}</table>
      <button type="button" id="decide" class="btn btn-primary">送信</button>
    </div>

    <div id="result" class="col-sm">
      <img class="img img-fluid" src="">
    </div>

    <div id="table" class="table table-striped col-sm table-responsive">
    </div>
  </div>
</div>

{% endblock %}



<!-- <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script> -->

{% block script %}

<script>
  $(function() {
    $("#decide").click(function() {
      $.ajax({
        url: "/record/ajax_chart/",
        type: "GET",
        data: {
          'school_name': $('#school_name_selector').val(),
          'year': $('#id_year').val(),
          'style': $('#id_style').val(),
          'distance': $('#id_distance').val(),
          'sex': $('#id_sex').val(),
        },
        dataType: 'json',
        success: function(response) {
          var image_src = 'data:image/png;base64,' + response.image;
          $('.img').attr('src', image_src);
          // $('.img').fadeIn(800);
          // response.table.attr('id', 'table1');



          $('#table').html(response.table);
          $('.dataframe').attr('id', 'table1');
          $('#table1').DataTable();
        },
        failure: function(responce) {
          alert('Got an error dude');
        },
      });
    });
    return false;
  });
</script>

{% endblock %}

swim/record/templates/record/daymenu_detail.html
{% extends 'base.html' %}
{% block script_head %}

<link href="https://cdn.pydata.org/bokeh/release/bokeh-0.12.14.min.css" rel="stylesheet" type="text/css">
<link href="https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.14.min.css" rel="stylesheet" type="text/css">
<link href="https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.14.min.css" rel="stylesheet" type="text/css">
<script src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.14.min.js"></script>
<script src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.14.min.js"></script>
<script src="https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.14.min.js"></script>
{{ script|safe }}
{% endblock %}

{% block content %}


{% for training in object.trainingmenus.all %}
{{ training }}
{% for time in training.get_times %}
<p>{{ time }}</p>
{% endfor %}

{% endfor %}



{{ div|safe }}

<hr>
<div>
  {% for t in training.all %}
  <p>{{ t.daymenu.date }}</p>
{% if t.get_times %}
  <p>{{ t.get_times }}</p>
  {% endif %}
  {% endfor %}
  </div>

{% endblock %}

swim/record/templates/record/daymenu_list.html
{% extends "base.html" %}


{% block content %}


<!-- <div class="card">
  <div class="card-header">
  </div>
  <div class="card-body"> -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal3">
  Launch demo modal
</button>
<div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModal3Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModal3Label"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% include 'input.html' %}
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      <div class="modal-footer">

        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


  <!-- </div>
</div> -->


<div class="container my-3">
  <h2 class="my-3">練習記録一覧</h2>
  <!-- <div class="row"> -->

    {% for menu in request_users_daymenus %}
    <!-- <div class="col-6"> -->
      <div class="card mb-5">
        <div class="card-header">
          <a href="{% url 'detail' menu.pk %}"><h3>{{ menu.date }}</h3></a>
        </div>
        <div class="card-body">

          {% for trainingmenu in menu.trainingmenus.all %}


          <p>メインメニュー : {{ trainingmenu.menu_name}}</p>
          <p>スタイル : {{ trainingmenu.style}}</p>
          <p>距離 : {{ trainingmenu.distance}}メートル</p>


          <table class="table table-striped table-sm">
            <thead>
              <tr>
                <th>本数</th>
                <th>Time</th>
              </tr>
            </thead>
            <tbody>
              {% for time in trainingmenu.times.all %}
              <tr>
                <th>{{ time.pk }}</th>
                <td>{{ time.time }}秒</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <!-- <img src={{img}} class='img-fluid'> -->
          <hr>
          {% endfor %}


          <p class="font-weight-bold">Score: {{ menu.score }} point.<p>
              <p>{{ menu.reflection }}</p>
        </div>
      </div>
    <!-- </div> -->
    {% endfor %}
  <!-- </div> -->
</div>

{% endblock %}


{% block script %}
{% include 'input.js' %}
{% endblock %}

swim/record/templates/record/index.html
{% extends 'base.html' %}
{% load static %}

{%block header%}

<div class="row">
  <div class="col-sm-3">
    <p class="h5">{{ user.user_info.generation }}期</p>
    {% if user.firstname %}
      <p>{{ user.firstname }} {{ user.familyname }}</p>
      {% else %}
      <p>{{ user.username }}</p>
    {% endif %}
    <p>{{ user.user_info.style }}</p>
    <p>{{ user.username }}</p>
  </div>
  <div class="col-sm-3">
    <img src="{% static 'img/kikuta1.png' %}" class="img img-fluid">
  </div>
</div>

{%endblock%}


{% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header" role="tab" id="headingOne">
          <h5 class="mb-0">
      <a data-toggle="collapse" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne" class="collapsed">This Week</a>
     </h5>
        </div>

        <div id="collapseOne" class="collapse" role="rabpanel" aria-labelledby="headingOne">

          <div class="card-body">
            <div class="table-responsive">
              <table id="table1" class="table table-sm table-striped text-nowrap">
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Name</th>
                    <th>Menue</th>
                    <th>Style</th>
                    <th>Distance</th>
                    <th>Num</th>
                    <th>Time</th>
                    <th>Is Rest</th>
                  </tr>
                </thead>
                <tbody>
                  {% for time in timelist_week %}
                  <tr>
                    <td>{{ time.training.date }}</td>
                    <td>{{ time.training.user }}</td>
                    <td>{{ time.training.menue_name }}</td>
                    <td>{{ time.training.style }}</td>
                    <td>{{ time.training.distance }}</td>
                    <td>{{ time.num_of_swim }}</td>
                    <td>{{ time.time_str }}</td>
                    <td>{{ time.rest }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card">
        <div class="card-header" role="tab" id="headingTwo">
          <h5 class="mb-0">
          <a class="collapsed" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            This Month
          </a>
        </h5>
        </div>
        <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
          <div class="card-body">

            <div class="table-responsive">
              <table id="table2" class="table table-sm table-striped text-nowrap">
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Name</th>
                    <th>Menue</th>
                    <th>Style</th>
                    <th>Distance</th>
                    <th>Num</th>
                    <th>Time</th>
                    <th>Is Rest</th>
                  </tr>
                </thead>
                <tbody>
                  {% for time in timelist_month %}
                  <tr>
                    <td>{{ time.training.date }}</td>
                    <td>{{ time.training.user }}</td>
                    <td>{{ time.training.menue_name }}</td>
                    <td>{{ time.training.style }}</td>
                    <td>{{ time.training.distance }}</td>
                    <td>{{ time.num_of_swim }}</td>
                    <td>{{ time.time_str }}</td>
                    <td>{{ time.rest }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>

          </div>
        </div>
      </div>
    </div>



  </div>
</div>



<hr class="my-3">



<div class="jumbotron my-3">
  <div class="media">
    <a href="{% url 'input_data' %}"><img src="{% static 'img/kikuta1.png' %}" alt="kikuta!" class="img img-fluid d-flex aline-self-start mr-3" width=80, height=80></a>
    <div class="media-body">
      <h5 class="mt-0">練習のタイムを記録</h5>
      <p>練習のタイムを記録するページ</p>
    </div>
  </div>
</div>



<hr class="my-3">



<div class="jumbotron my-3">
  <div class="media">
    <a href="{% url 'chart_view' %}"><img src="{% static 'img/sanai1.jpg' %}" alt="sanai!" class="img img-fluid d-flex aline-self-start mr-3" width=80 height=80></a>
    <div class="media-body">
      <h5 class="mt=0">16校の結果を検索</h5>
      <p>116校の結果を検索して、一覧とグラフが見れるページ6校の結果を検索して、一覧とグラフが見れるページ6校の結果を検索して、一覧とグラフが見れるページ校の結果を検索して、一覧とグラフが見れるページ</p>
    </div>
  </div>
</div>


<hr class="my-3">


<div class="jumbotron my-3">
  <div class="media">
    <a href="{% url 'index' %}"><img src="{% static 'img/banana.png' %}" class="img img-fluid d-flex aline-self-start mr-3" width=80 height=80 alt="banana!"></a>
    <div class="media-body">
      <h5 class="mt-0">メッセージ</h5>
      <p>意見を投稿するページ16校の結果を検索して、一覧とグラフが見れるページ6校の結果を検索して、一覧とグラフが見れるページ16校の結果を検索して、一覧とグラフが見れるページ6校の結果を検索して、一覧とグラフが見れるページ</p>
    </div>
  </div>
</div>


{% endblock %} {% block content %}{% endblock %}

swim/record/templates/record/input_data.html
{% extends 'base.html' %}
{% block body %}

<div class="content-fluid mb-5">
<div class="row justify-content-center">

<div class="card">

<div class="card-header">
<h5>練習のタイムを記録</h5>
</div>


<div class="card-body">


  <form method="post" action="{% url 'input_data' %}" id="form">

<div class="container">
<div class="row">
<div class="col">



    <div class="form-group">
      {% csrf_token %}
        <label for="id_date">日付:</label>
        {{form.date}}<br>
        <div class="input-group input-group form-inline mt-3">
        <label for="id_menue_name">メニュー:</label> {{ form.menue_name }}
        <label for="id_style">スタイル:</label> {{ form.style }}
        <label for="id_distance">距離:</label> {{ form.distance }}
        <strong>m</strong>
      </div>

<hr class="my-3">


      <ol id="result">
        <li class="form mt-3">
          <div class="form form-row form-inline">

              <div class="input-group">{{form2.m_10}}{{form2.m_1}}</div>
              <label for="id_s_10">:</label>
              <div class="input-group">{{form2.s_10}}{{form2.s_1}}</div>
              <label for="id_ms_10">:</label>
              <div class="input-group">{{form2.ms_10}}{{form2.ms_1}}</div>
            
              <div>{{form2.rest}}</div>
          </div>
        </li>
      </ol>

      <button type="button" id="one_more" class="btn btn-secondary">one more</button><br>
</div>

	
<div class="col">
	{{form.point}}
	{{form.impression}}
      <input type="submit" class="btn btn-primary mt-3" value='submit' />
    </div>
  
</div>
</div>
</div>
   </form>


</div>
</div>
</div>
</div>

{% endblock %}

{% block script %}

<!-- <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script> -->

<script>
  $(function() {
    $('form').on('click', '#one_more', function() {

      var m_10 = $('.m_10:eq(-1) option:selected').val();
      var m_1 = $('.m_1:eq(-1) option:selected').val();
      var s_10 = $('.s_10:eq(-1) option:selected').val();
      var s_1 = $('.s_1:eq(-1) option:selected').val();
      var ms_10 = $('.ms_10:eq(-1) option:selected').val();
      var ms_1 = $('.ms_1:eq(-1) option:selected').val();

      var lastform = $('#result > li:eq(-1)').clone();
      lastform.find('.m_10').val(m_10);
      lastform.find('.m_1').val(m_1);
      lastform.find('.s_10').val(s_10);
      lastform.find('.s_1').val(s_1);
      lastform.find('.ms_10').val(ms_10);
      lastform.find('.ms_1').val(ms_1);

      $('#result').append(lastform);
    });
  });
</script>

{% endblock %}

swim/record/templates/record/logout.html
{% extends "base.html" %}
{% block body %}

<div class="card mx-auto" style="width: 400px;">
<div class="card-header">
</div>
<div class="card-body">
  <h2><p>ログアウトしました</p></h2>
  <h2><div><a class="btn btn-secondary" href="{% url 'login' %}">ログインページへ</a></div></h2>
</div>
</div>
{% endblock %}