swim/record/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView

from . import views


# app_name = 'record'

urlpatterns = [
    url(r'^login', LoginView.as_view(template_name='record/login.html'), name='login'),
    url(r'^logout', LogoutView.as_view(template_name='record/logout.html'), name='logout'),

    url(r'^new', views.new, name='new'),
    url(r'^create', views.create, name='create'),

    url(r'^$', views.Index, name='index'),

    url(r'^input_data/$', views.Input_Data, name='input_data'),

    url(r'^ajax_chart/', views.ajax_chart, name='ajax_chart'),
    url(r'^chart/$', views.ChartView, name='chart_view'),

    url(r'^player_list/$', views.Player_List, name='player_list'),
    url(r'^player/(?P<pk>[0-9]+)/$', views.Player_Info.as_view(), name='player_info'),
    url(r'^player_update/(?P<pk>[0-9]+)/$', views.Player_Update.as_view(), name='player_update'),


    url(r'^top/$', views.TopPage.as_view(), name='top'),
    url(r'^top/(?P<pk>[0-9]+)/$', views.Training_Detail.as_view(), name='detail'),
]

swim/swim/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^record/', include('record.urls')),
]

swim/record/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

SEX_CHOICES = (
    ('M', 'Man'),
    ('W', 'Woman'),
    ('O', 'Other')
)

STYLE_CHOICES = (
    ('Fr', 'Fr'),
    ('Ba', 'Ba'),
    ('Br', 'Br'),
    ('Fly', 'Fly'),
    ('IM', 'IM'),

)

DISTANCE_CHOICES = (
    (25, 25),
    (50, 50),
    (100, 100),
    (200, 200),
    (400, 400),
    (800, 800),
)

ONE_TO_TEN_CHOICES = [
    (num, num) for num in range(0, 11)
]

ONE_TO_SIXTY_CHOICE = [
    (num, num) for num in range(0, 60)
]


class Menue(models.Model):
    menue_name = models.CharField(max_length=15, verbose_name='メニュー')

    def __str__(self):
        return self.menue_name


class DayMenu(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(default=timezone.now, null=True, blank=False)
    score = models.PositiveIntegerField('点数', null=True, blank=True)
    reflection = models.TextField('感想', max_length=1000, null=True, blank=True)

    def get_trainings(self):
        t = TrainingMenu.objects.filter(daymenu=self)
        return [i for i in t]

    def __str__(self):
        return '{}, {}, {}'.format(self.pk, self.user, self.date)


class TrainingMenu(models.Model):
    daymenu = models.ForeignKey(DayMenu, on_delete=models.CASCADE, null=True, blank=True, related_name='trainingmenus')
    order = models.PositiveIntegerField('メニューNo.', null=True, blank=True)
    menu_name = models.ForeignKey(Menue, on_delete=models.CASCADE, null=True, blank=True)
    style = models.CharField(choices=STYLE_CHOICES, max_length=10, null=True, blank=False)
    distance = models.IntegerField(choices=DISTANCE_CHOICES, null=False)
    # graph = views.make_img()

    def get_times(self):
        t = Result_Time.objects.filter(trainingmenu=self)
        return [i.time for i in t]

    def __str__(self):
        return '{}, {}'.format(self.daymenu.pk, self.menu_name)


class Result_Time(models.Model):
    trainingmenu = models.ForeignKey(TrainingMenu, on_delete=models.CASCADE, null=True, blank=True, related_name='times')
    order = models.IntegerField('本数', null=True)
    time = models.FloatField('タイム[s]', null=True, blank=True)
    rest = models.NullBooleanField('レスト', blank=True, default=False)

    def __str__(self):
        return '{}'.format(self.order)


class Rap_Time(models.Model):
    result_time = models.ForeignKey(Result_Time, on_delete=models.CASCADE, null=True, blank=True, related_name='raps')
    time = models.FloatField('タイム[s]', null=True, blank=True)

    def __str__(self):
        return '{}, {}'.format(int(self.pk)*50, self.time)


class User_Info(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    familyname = models.CharField('姓', max_length=15, null=True, blank=True)
    firstname = models.CharField('名', max_length=15, null=True, blank=True)
    sex = models.CharField('性別', max_length=5, choices=SEX_CHOICES, null=True, blank=True)
    generation = models.PositiveIntegerField('期', null=True, blank=True)
    style = models.CharField(choices=STYLE_CHOICES, max_length=10, null=True, blank=True)
    cource = models.PositiveIntegerField('コース', null=True, blank=True)
    is_manager = models.BooleanField('マネジャー', default=False)
    is_courch = models.BooleanField('コーチ', default=False)

    def __str__(self):
        return self.user.username

swim/record/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from .models import Menue, DayMenu, TrainingMenu, Result_Time, User_Info
import os
import pandas as pd


path = os.path.join(os.path.join(os.path.dirname(__file__), 'Result_all.csv'))
df = pd.read_csv(path)


class User_Info_Form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(User_Info_Form, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = User_Info
        # fields = '__all__'
        exclude = ['user', 'is_manager', 'is_courch', ]


class User_Update_Form(User_Info_Form, UserChangeForm):

    class Meta:
        model = User
        # model = User_Info
        fields = '__all__'
        # exclude = ['user', 'is_manager', 'is_courch', ]


class Menue_Form(forms.ModelForm):
    class Meta:
        model = Menue
        fields = '__all__'


class DayMenu_Form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DayMenu_Form, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = DayMenu
        fields = '__all__'


class TrainingMenu_Form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TrainingMenu_Form, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = TrainingMenu
        fields = '__all__'
        # menue_name = forms.ModelChoiceField(Menue.objects)


class Result_Time_Form(forms.ModelForm):
    NUMBER = [
        (num, num) for num in range(0, 10)
    ]
    m_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_10 custom-select'}))
    m_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_1 custom-select'}))
    s_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_10 custom-select'}))
    s_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_1 custom-select'}))
    ms_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_10 custom-select'}))
    ms_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_1 custom-select'}))

    rest = forms.BooleanField(required=False)

    class Meta:
        model = Result_Time
        fields = '__all__'
        widgets = {
            'time_minutes': forms.NumberInput(attrs={
                'name': 'time_minutes[]',
            }),
            'time_seconds': forms.NumberInput(attrs={
                'name': 'time_seconds[]',
            }),
            'time_seconds_micro': forms.NumberInput(attrs={
                'name': 'time_seconds_micro[]',
            }),
        }


class Rap_Time_Form(forms.Form):

    NUMBER = [
        (num, num) for num in range(0, 10)
    ]

    m_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_1_r custom-select'}))
    s_10_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_10_r custom-select'}))
    s_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_1_r custom-select'}))
    ms_10_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_10_r custom-select'}))
    ms_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_1 custom-select'}))


class Select_Form(forms.Form):
    year_list = sorted(list(set(df.Year.values)))
    style_list = sorted(list(set(df.Style.values)))
    distance_list = sorted(list(set(df.Distance.values)))
    sex_list = sorted(list(set(df.Sex.values)))

    YEAR_CHOICES = [(year, year) for year in year_list]
    STYLE_CHOICES = [(style, style) for style in style_list]
    DISTANCE_CHOICES = [(distance, distance) for distance in distance_list]
    SEX_CHOICES = [(sex, sex) for sex in sex_list]

    YEAR_CHOICES.append((year_list, 'all'))
    STYLE_CHOICES.append((style_list, 'all'))
    DISTANCE_CHOICES.append((distance_list, 'all'))
    SEX_CHOICES.append((sex_list, 'all'))


    year = forms.ChoiceField(choices=YEAR_CHOICES, label='年度', widget=forms.Select(attrs={'class': 'year custom-select'}))
    sex = forms.ChoiceField(choices=SEX_CHOICES, label='性別', widget=forms.Select(attrs={'class': 'sex custom-select'}))
    style = forms.ChoiceField(choices=STYLE_CHOICES, label='スタイル', widget=forms.Select(attrs={'class': 'style custom-select'}))
    # sex = forms.MultipleChoiceField(choices=SEX_CHOICES, label='性別', widget=forms.CheckboxSelectMultiple())
    # style = forms.ChoiceField(choices=STYLE_CHOICES, label='スタイル')
    distance = forms.ChoiceField(choices=DISTANCE_CHOICES, label='距離', widget=forms.Select(attrs={'class': 'distance custom-select'}))






# class Menu_Test_Form(forms.Form):
#     from record.models import STYLE_CHOICES, DISTANCE_CHOICES
#
#     date = forms.DateField(initial=timezone.now, widget=forms.SelectDateWidget(attrs={'class': 'form-control'}))
#
#     menu = forms.ChoiceField(choices=[(i.menue_name, i.menue_name) for i in Menue.objects.all()], widget=forms.Select(attrs={'class': 'custom-select'}))
#
#     style = forms.ChoiceField(choices=STYLE_CHOICES, widget=forms.Select(attrs={'class': 'custom-select'}))
#     distance = forms.ChoiceField(choices=DISTANCE_CHOICES, widget=forms.Select(attrs={'class': 'custom-select'}))
#     number = forms.ChoiceField(choices=[(num, num) for num in range(1, 31)], widget=forms.Select(attrs={'class': 'custom-select'}))
#     score = forms.ChoiceField(choices=[(num, num) for num in range(1, 6)], widget=forms.Select(attrs={'class': 'custom-select'}))
#     reflection = forms.CharField(max_length=1000, widget=forms.Textarea(attrs={'class': 'form-control'}))




# class Time_Form(forms.Form):
#     NUMBER = [
#         (num, num) for num in range(0, 10)
#     ]
#
#     m_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_10 custom-select'}))
#     m_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_1 custom-select'}))
#     s_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_10 custom-select'}))
#     s_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_1 custom-select'}))
#     ms_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_10 custom-select'}))
#     ms_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_1 custom-select'}))
#
#     rest = forms.BooleanField(required=False)


# class Rap_Form(forms.Form):
#     NUMBER = [
#         (num, num) for num in range(0, 10)
#     ]
#
#     m_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_1_r custom-select'}))
#     s_10_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_10_r custom-select'}))
#     s_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_1_r custom-select'}))
#     ms_10_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_10_r custom-select'}))
#     ms_1_r = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_1 custom-select'}))

# class Sample_Form(forms.Form):
#     def __init__(self, num=3, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for i in range(self.num):
#             self['value_{}'.format(i)] = forms.CharField(max_length=10)

    # NUMBER = [
    #     (num, num) for num in range(0, 10)
    # ]
    #
    # m_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_10 custom-select'}))
    # m_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'm_1 custom-select'}))
    # s_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_10 custom-select'}))
    # s_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 's_1 custom-select'}))
    # ms_10 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_10 custom-select'}))
    # ms_1 = forms.ChoiceField(choices=NUMBER, widget=forms.Select(attrs={'class': 'ms_1 custom-select'}))
    #
    # rest = forms.BooleanField(required=False)

swim/record/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang='ja'>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

  <!-- DataTable CSS -->
  <!-- <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'styles_base.css' %}">
  {% block script_head %}{% endblock %}
</head>

<!-- ****************************************************************************************** -->

<body>
  <header>
    <div class="container">
      {% block header %}{% endblock %}
    </div>
  </header>


  <!-- ****************************************************************************************** -->


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'input_data' %}">Time Input</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'chart_view' %}">Chart</a>
        </li>
        {% if user.pk %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'player_info' user.pk %}">Profile</a>
        </li>
        {% endif %}
        {% if user.user_info.is_manager %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'player_list' %}">Player List</a>
        </li>
        {% endif %}
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

<!-- ****************************************************************************************** -->

  <div class="container-fluid my-5 mx-2">
    <!-- <div class="container"> -->
      <div class="jumbotron bg-light">
        {% block body %}
        {% endblock %}
      </div>
    <!-- </div> -->
  </div>

  <!-- ****************************************************************************************** -->

{% block content %}
{% endblock %}


<footer class="container-fluid">
  <div><a class="btn btn-lg btn-outline-secondary mb-3" href="{% url 'logout' %}">ログアウト</a></div>
  <p>otninast38.inc</p>
</footer>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

<!-- DataTable -->
<script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>

<script>
$(function(){
$('#table1').DataTable();
$('#table2').DataTable();
});
// $(document).ready(function() {
//     $("#table1").DataTable();
// } );
</script>
{% block script %}{% endblock %}

</body>
</html>

swim/record/templates/input.html
<div class="content-fluid mb-5">
  <div class="row justify-content-center">

    <div class="card">

      <div class="card-header">
        <h5>練習のタイムを記録</h5>
      </div>

      <div class="card-body">
        <form method="post" action="" id="form">
          <div class="container">
            <div class="row">
              <div class="col">
                <div class="form-group">
                  {% csrf_token %}
                  <label for="id_date">日付:</label>
                  {{daymenu_form.date}}<br>
                  <div class="input-group input-group form-inline mt-3">
                    <label for="id_menue_name">メニュー:</label> {{ trainingmenu_form.menu_name }}
                    <label for="id_style">スタイル:</label> {{ trainingmenu_form.style }}
                    <label for="id_distance">距離:</label> {{ trainingmenu_form.distance }}
                    <strong>m</strong>
                  </div>

                  <hr class="my-3">

                  <ol id="result">
                    <li class="form mt-3">
                      <div class="form form-row form-inline result_time">
                        <label for="id_m_10">&nbsp本目&nbsp</label>
                        <div class="input-group">{{result_time_form.m_10}}{{result_time_form.m_1}}</div>
                        <label for="id_s_10">&nbsp:&nbsp</label>
                        <div class="input-group">{{result_time_form.s_10}}{{result_time_form.s_1}}</div>
                        <label for="id_ms_10">&nbsp:&nbsp</label>
                        <div class="input-group">{{result_time_form.ms_10}}{{result_time_form.ms_1}}</div>
                        <div>&nbsp&nbsp{{result_time_form.rest}}</div>
                      </div>
                    </li>
                  </ol>
                  <button type="button" id="one_more" class="btn btn-secondary">one more</button><br>
                </div>
                <div class="col">
                  {{daymenu_form.score}}
                  {{daymenu_form.reflection}}
                  <input type="submit" class="btn btn-primary mt-3" value='submit' />
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>